-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.teams;

CREATE TABLE IF NOT EXISTS public.teams
(
    product_owner bigint NOT NULL,
    backend_developer bigint,
    frontend_developer bigint,
    data_engineer bigint,
    team_num bigint NOT NULL,
    PRIMARY KEY (team_num),
    UNIQUE (team_num)
);

DROP TABLE IF EXISTS public.products;

CREATE TABLE IF NOT EXISTS public.products
(
    product_id bigint NOT NULL,
    product_name character varying,
    team bigint NOT NULL,
    PRIMARY KEY (product_id),
    UNIQUE (product_id)
);

DROP TABLE IF EXISTS public.customers;

CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id bigint NOT NULL,
    customer_name character varying,
    customer_adress character varying,
    product_id bigint,
    PRIMARY KEY (customer_id)
);

DROP TABLE IF EXISTS public.domens;

CREATE TABLE IF NOT EXISTS public.domens
(
    domen_name character varying NOT NULL,
    customer_id bigint,
    PRIMARY KEY (domen_name)
);

DROP TABLE IF EXISTS public.employees;

CREATE TABLE IF NOT EXISTS public.employees
(
    first_name character varying NOT NULL,
    second_name character varying NOT NULL,
    email character varying,
    post_adress character varying,
    empl_num bigint,
    PRIMARY KEY (empl_num)
);

ALTER TABLE IF EXISTS public.teams
    ADD CONSTRAINT owner FOREIGN KEY (product_owner)
    REFERENCES public.employees (empl_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.teams
    ADD FOREIGN KEY (backend_developer)
    REFERENCES public.employees (empl_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.teams
    ADD FOREIGN KEY (frontend_developer)
    REFERENCES public.employees (empl_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.teams
    ADD FOREIGN KEY (data_engineer)
    REFERENCES public.employees (empl_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT team FOREIGN KEY (team)
    REFERENCES public.teams (team_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customers
    ADD CONSTRAINT products FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.domens
    ADD CONSTRAINT customer FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;