-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.students
(
    student_id integer,
    student_name character varying COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.teachers
(
    teacher_id integer,
    teacher_name character varying COLLATE pg_catalog."default"
);
END;