-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Member_IT_team"
(
    pk_member_id integer NOT NULL,
    fk_groub_id integer NOT NULL,
    fk_task_id integer NOT NULL,
    name character varying NOT NULL,
    gender character varying NOT NULL,
    address character varying NOT NULL,
    PRIMARY KEY (pk_member_id)
);

CREATE TABLE IF NOT EXISTS public.task
(
    fk_task_id integer NOT NULL,
    name_of_task character varying NOT NULL,
    PRIMARY KEY (fk_task_id)
);

CREATE TABLE IF NOT EXISTS public."group"
(
    fk_group_id integer NOT NULL,
    group_name character varying NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product
(
    pk_product_id integer NOT NULL,
    fk_group_id integer NOT NULL,
    "fk_customer _id" integer NOT NULL,
    product_name character varying NOT NULL,
    PRIMARY KEY (pk_product_id)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    pk_customer_id integer NOT NULL,
    customer_name character varying NOT NULL,
    customer_address character varying NOT NULL,
    customer_gender character varying,
    PRIMARY KEY (pk_customer_id)
);

ALTER TABLE IF EXISTS public."Member_IT_team"
    ADD CONSTRAINT task_id FOREIGN KEY (fk_task_id)
    REFERENCES public.task (fk_task_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Member_IT_team"
    ADD CONSTRAINT group_id FOREIGN KEY (fk_groub_id)
    REFERENCES public."group" (fk_group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."group"
    ADD CONSTRAINT product_id FOREIGN KEY (fk_group_id)
    REFERENCES public.product (fk_group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT customer_id FOREIGN KEY ("fk_customer _id")
    REFERENCES public.customer (pk_customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;