-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.product
(
    product_id integer,
    product_name character varying,
    fk_customer_id integer,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    customer_id integer,
    customer_name character varying,
    customer_adress character varying,
    email character varying,
    domain_id integer,
    PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.team
(
    team_id integer,
    product integer,
    PRIMARY KEY (team_id)
);

CREATE TABLE IF NOT EXISTS public.members_of_team
(
    member_id integer NOT NULL,
    member_name character varying,
    gender character varying,
    dob date,
    teamid integer,
    title integer,
    PRIMARY KEY (member_id)
);

CREATE TABLE IF NOT EXISTS public.domain
(
    domain_id integer,
    domain_name character varying,
    PRIMARY KEY (domain_id)
);

CREATE TABLE IF NOT EXISTS public.title
(
    title_id integer,
    title_name character varying,
    title_description character varying
);

ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT costumer FOREIGN KEY (fk_customer_id)
    REFERENCES public.customer (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customer
    ADD CONSTRAINT domain FOREIGN KEY (domain_id)
    REFERENCES public.domain (domain_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.team
    ADD CONSTRAINT product FOREIGN KEY (product)
    REFERENCES public.product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.members_of_team
    ADD FOREIGN KEY (teamid)
    REFERENCES public.team (team_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.members_of_team
    ADD CONSTRAINT "title id" FOREIGN KEY (title)
    REFERENCES public.title (title_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;