-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Teams"
(
    "teamID" bigint NOT NULL,
    "teamName" character varying NOT NULL,
    product bigint,
    PRIMARY KEY ("teamID")
);

CREATE TABLE IF NOT EXISTS public."Members"
(
    "memberID" bigint NOT NULL,
    "memberName" character varying NOT NULL,
    "dateOfBirth" date NOT NULL,
    team bigint,
    title bigint NOT NULL,
    PRIMARY KEY ("memberID")
);

CREATE TABLE IF NOT EXISTS public."Products"
(
    "productID" bigint NOT NULL,
    "productName" character varying NOT NULL,
    customer bigint,
    description character varying,
    PRIMARY KEY ("productID")
);

CREATE TABLE IF NOT EXISTS public."Customers"
(
    "customerID" bigint NOT NULL,
    "customerName" character varying NOT NULL,
    domain bigint,
    email character varying,
    address character varying,
    "phoneNumber" character varying,
    PRIMARY KEY ("customerID")
);

CREATE TABLE IF NOT EXISTS public."Titles"
(
    "titleID" bigint NOT NULL,
    title character varying NOT NULL,
    description character varying,
    PRIMARY KEY ("titleID")
);

CREATE TABLE IF NOT EXISTS public."Domains"
(
    "domainID" bigint NOT NULL,
    domain character varying NOT NULL,
    description character varying,
    PRIMARY KEY ("domainID")
);

ALTER TABLE IF EXISTS public."Teams"
    ADD CONSTRAINT product FOREIGN KEY (product)
    REFERENCES public."Products" ("productID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Members"
    ADD CONSTRAINT team FOREIGN KEY (team)
    REFERENCES public."Teams" ("teamID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Members"
    ADD CONSTRAINT title FOREIGN KEY (title)
    REFERENCES public."Titles" ("titleID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Products"
    ADD CONSTRAINT customer FOREIGN KEY (customer)
    REFERENCES public."Customers" ("customerID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Customers"
    ADD CONSTRAINT domain FOREIGN KEY (domain)
    REFERENCES public."Domains" ("domainID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;